language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# command to run tests, e.g. python setup.py test
script: google_appengine/run_tests.py

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip -nv
  - unzip -q google_appengine_1.9.6.zip
